In [46]:
from scipy import sparse
from scipy import linalg
import numpy as np
import pandas as pd

In [47]:
arr = [ [0.0, 0.8, 0.6, 0.1, 0.0, 0.0], 
        [0.8, 0.0, 0.9, 0.0, 0.0, 0.0], 
        [0.6, 0.9, 0.0, 0.0, 0.0, 0.2], 
        [0.1, 0.0, 0.0, 0.0, 0.6, 0.7], 
        [0.0, 0.0, 0.0, 0.6, 0.0, 0.8], 
        [0.0, 0.0, 0.2, 0.7, 0.8, 0.0]]
arr = np.array(arr)

In [51]:
eigenvalue, eigenvector = linalg.eig(arr)
print(arr)
df = pd.DataFrame(data = eigenvector, index = eigenvalue)
df = df.round(3)
print(df)

[[0.  0.8 0.6 0.1 0.  0. ]
 [0.8 0.  0.9 0.  0.  0. ]
 [0.6 0.9 0.  0.  0.  0.2]
 [0.1 0.  0.  0.  0.6 0.7]
 [0.  0.  0.  0.6 0.  0.8]
 [0.  0.  0.2 0.7 0.8 0. ]]
                               0      1      2      3      4      5
(1.5944077858105132+0j)   -0.479 -0.253 -0.173  0.461 -0.570 -0.373
(1.3546893778605615+0j)   -0.533 -0.309  0.651 -0.438  0.056 -0.034
(-0.9927194908153985+0j)  -0.519 -0.240 -0.565 -0.005  0.477  0.356
(-0.8320768505272272+0j)  -0.255  0.484 -0.107 -0.303 -0.561  0.532
(-0.48211773069469743+0j) -0.247  0.524 -0.251 -0.366  0.185 -0.658
(-0.6421830916337516+0j)  -0.301  0.524  0.391  0.608  0.309  0.129
